"""Stage 13: Deterministic 2D LiDAR Scan Recording and Replay System.

===============================================================================
MANDATORY REPLAY SPECIFICATION & SOURCE METADATA SEPARATION:
Because physical 2D LiDAR readings are not yet available, this replay system
provides a deterministic mechanism to record, serialize, and replay laser scan
datasets for reproducible testing and future real-world sensor data ingestion.

STRICT METADATA AUDIT CONTRACT:
1. Every replay dataset MUST contain an explicit header declaring its `source_type`:
   - 'synthetic': Generated by software simulation test harnesses.
   - 'real_ros2': Ingested from physical ROS 2 /scan sensor streams.
   - 'recorded': Captured field data from mining trials.
2. The dataset MUST declare `hardware_validated` (boolean). For synthetic datasets,
   this is strictly False.
3. The replayer MUST REJECT any dataset whose `source_type` is missing, ambiguous,
   or invalid with an explicit ValueError.
4. Synthetic data must NEVER be labeled or represented as real sensor data.
===============================================================================
"""

from __future__ import annotations

import json
import math
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator, Sequence

from src.perception.lidar_2d import LaserScan2D, PerceptionSource

VALID_SOURCE_TYPES = {"synthetic", "real_ros2", "recorded"}
REPLAY_SPEC_VERSION = "1.0"


class AmbiguousReplayDatasetError(ValueError):
    """Raised when a replay dataset lacks required source_type metadata or contains invalid attributes."""
    pass


class LiDARScanRecorder:
    """Serializes 2D LiDAR scans to deterministic JSON Lines format with explicit provenance."""

    def __init__(
        self,
        output_path: Path | str,
        source_type: str,
        hardware_validated: bool = False,
        description: str = "",
        sensor_model: str = "2D Planar LiDAR",
    ) -> None:
        """Initialize recorder.

        Args:
            output_path: Destination file path (.jsonl).
            source_type: 'synthetic', 'real_ros2', or 'recorded'.
            hardware_validated: Explicit boolean. Must be False for synthetic data.
            description: Human-readable dataset description.
            sensor_model: Sensor specification or manufacturer model.
        """
        if source_type not in VALID_SOURCE_TYPES:
            raise AmbiguousReplayDatasetError(
                f"Invalid source_type: '{source_type}'. Must be one of {sorted(VALID_SOURCE_TYPES)}"
            )

        if source_type == "synthetic" and hardware_validated:
            raise ValueError("Safety violation: Synthetic data cannot be marked as hardware_validated=True")

        self.output_path = Path(output_path)
        self.source_type = source_type
        self.hardware_validated = hardware_validated
        self.description = description
        self.sensor_model = sensor_model
        self.scan_count = 0
        self._file = None

        # Ensure parent directories exist
        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        self._open()

    def _open(self) -> None:
        self._file = open(self.output_path, "w", encoding="utf-8")
        # Write metadata header
        header = {
            "type": "metadata",
            "spec_version": REPLAY_SPEC_VERSION,
            "source_type": self.source_type,
            "hardware_validated": self.hardware_validated,
            "sensor_model": self.sensor_model,
            "description": self.description,
            "created_at_utc": datetime.now(timezone.utc).isoformat(),
            "disclaimer": (
                "HARDWARE-READY / REAL-SENSOR-READY, BUT NOT PHYSICALLY VALIDATED"
                if not self.hardware_validated
                else "PHYSICALLY VALIDATED REAL SENSOR DATA"
            ),
        }
        self._file.write(json.dumps(header) + "\n")
        self._file.flush()

    def record_scan(self, scan: LaserScan2D | dict[str, Any]) -> None:
        """Record a single planar laser scan."""
        if self._file is None:
            raise IOError("Recorder is closed")

        if isinstance(scan, LaserScan2D):
            record = {
                "type": "scan",
                "index": self.scan_count,
                "frame_id": scan.frame_id,
                "timestamp_ns": scan.timestamp_ns,
                "angle_min": round(scan.angle_min, 6),
                "angle_max": round(scan.angle_max, 6),
                "angle_increment": round(scan.angle_increment, 8),
                "time_increment": scan.time_increment,
                "scan_time": scan.scan_time,
                "range_min": scan.range_min,
                "range_max": scan.range_max,
                "mounting_yaw_offset_rad": round(scan.mounting_yaw_offset_rad, 6),
                "mounting_x_offset_m": round(scan.mounting_x_offset_m, 6),
                "mounting_y_offset_m": round(scan.mounting_y_offset_m, 6),
                "ranges": [round(r, 4) if not (math.isnan(r) or math.isinf(r)) else None for r in scan.ranges],
                "intensities": [round(i, 2) for i in scan.intensities],
            }
        elif isinstance(scan, dict):
            record = dict(scan)
            record["type"] = "scan"
            record["index"] = self.scan_count
        else:
            raise TypeError(f"Unsupported scan type for recording: {type(scan).__name__}")

        self._file.write(json.dumps(record) + "\n")
        self._file.flush()
        self.scan_count += 1

    def close(self) -> None:
        """Close recorded file."""
        if self._file is not None and not self._file.closed:
            self._file.close()
            self._file = None

    def __enter__(self) -> LiDARScanRecorder:
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        self.close()


class LiDARScanReplayer(PerceptionSource):
    """Replays deterministic recorded 2D planar laser scans with strict provenance checking."""

    def __init__(self, dataset_path: Path | str) -> None:
        """Initialize replayer from a serialized JSON Lines dataset.

        Args:
            dataset_path: Path to .jsonl dataset file.
        """
        self.dataset_path = Path(dataset_path)
        if not self.dataset_path.exists():
            raise FileNotFoundError(f"Replay dataset not found: {self.dataset_path}")

        self.metadata: dict[str, Any] = {}
        self.scans: list[LaserScan2D] = []
        self._current_index = 0

        self._load_dataset()

    def _load_dataset(self) -> None:
        """Load and validate dataset header and scan records."""
        with open(self.dataset_path, "r", encoding="utf-8") as f:
            lines = [line.strip() for line in f if line.strip()]

        if not lines:
            raise AmbiguousReplayDatasetError("Replay dataset file is empty")

        # First line MUST be valid metadata
        try:
            header = json.loads(lines[0])
        except Exception as e:
            raise AmbiguousReplayDatasetError(f"Malformed metadata header in dataset: {e}")

        if not isinstance(header, dict) or header.get("type") != "metadata":
            raise AmbiguousReplayDatasetError(
                "Dataset missing required metadata header on line 1"
            )

        source_type = header.get("source_type")
        if not source_type or source_type not in VALID_SOURCE_TYPES:
            raise AmbiguousReplayDatasetError(
                f"Dataset rejected: missing or ambiguous source_type '{source_type}'. "
                f"Must be one of {sorted(VALID_SOURCE_TYPES)}"
            )

        if "hardware_validated" not in header:
            raise AmbiguousReplayDatasetError(
                "Dataset rejected: missing mandatory 'hardware_validated' flag"
            )

        self.metadata = header
        self.source_type = str(source_type)
        self.hardware_validated = bool(header["hardware_validated"])

        # Parse scan lines
        for line_num, line in enumerate(lines[1:], start=2):
            try:
                rec = json.loads(line)
            except Exception as e:
                raise ValueError(f"Corrupted scan record on line {line_num}: {e}")

            if rec.get("type") != "scan":
                continue

            scan = LaserScan2D.from_dict(rec)
            self.scans.append(scan)

    # -------------------------------------------------------------------------
    # PerceptionSource Interface Implementation
    # -------------------------------------------------------------------------

    def get_source_name(self) -> str:
        return f"LiDARScanReplayer({self.source_type}, valid={self.hardware_validated})"

    def is_synthetic(self) -> bool:
        """Return True if the underlying recorded data is synthetic."""
        return self.source_type == "synthetic"

    def get_sensor_dimensionality(self) -> str:
        return "2D"

    def get_latest_scan(self) -> LaserScan2D | None:
        """Return the next scan in the playback sequence (sequential playback)."""
        if not self.scans:
            return None
        scan = self.scans[self._current_index % len(self.scans)]
        self._current_index += 1
        return scan

    # -------------------------------------------------------------------------
    # Sequence Access Helpers
    # -------------------------------------------------------------------------

    def __len__(self) -> int:
        return len(self.scans)

    def __iter__(self) -> Iterator[LaserScan2D]:
        return iter(self.scans)

    def __getitem__(self, index: int) -> LaserScan2D:
        return self.scans[index]

    def reset(self) -> None:
        """Reset playback index to beginning."""
        self._current_index = 0
